
package br.com.asf.service.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CompanyWSService", targetNamespace = "http://ws.service.asf.com.br/", wsdlLocation = "http://localhost:8080/ASF/CompanyWS?wsdl")
public class CompanyWSService
    extends Service
{

    private final static URL COMPANYWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPANYWSSERVICE_EXCEPTION;
    private final static QName COMPANYWSSERVICE_QNAME = new QName("http://ws.service.asf.com.br/", "CompanyWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ASF/CompanyWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPANYWSSERVICE_WSDL_LOCATION = url;
        COMPANYWSSERVICE_EXCEPTION = e;
    }

    public CompanyWSService() {
        super(__getWsdlLocation(), COMPANYWSSERVICE_QNAME);
    }

    public CompanyWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPANYWSSERVICE_QNAME, features);
    }

    public CompanyWSService(URL wsdlLocation) {
        super(wsdlLocation, COMPANYWSSERVICE_QNAME);
    }

    public CompanyWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPANYWSSERVICE_QNAME, features);
    }

    public CompanyWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompanyWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CompanyWS
     */
    @WebEndpoint(name = "CompanyWSPort")
    public CompanyWS getCompanyWSPort() {
        return super.getPort(new QName("http://ws.service.asf.com.br/", "CompanyWSPort"), CompanyWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompanyWS
     */
    @WebEndpoint(name = "CompanyWSPort")
    public CompanyWS getCompanyWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.service.asf.com.br/", "CompanyWSPort"), CompanyWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPANYWSSERVICE_EXCEPTION!= null) {
            throw COMPANYWSSERVICE_EXCEPTION;
        }
        return COMPANYWSSERVICE_WSDL_LOCATION;
    }

}
